export const DEFAULT_FORM_VALUES = {
  clientInfo: {
    name: '',
    phone: '',
    folio: '',
  },
  generalInfo: {
    dateTime: new Date().toISOString(),
    derivationBy: '',
    address: {
      street: '',
      postalCode: '',
      city: '',
    },
    building: '',
    cmIdentification: '',
    floor: '',
    situation: '',
    comment: '',
  },
  photoBeforeWork: {
    photo: null,
  },
  oldMeter: {
    type: '',
    generation: '',
    preserved: false,
    linkyRefusal: undefined,
    serialNumber: '',
    key: '',
    dayIndex: '',
    nightIndex: '',
    indexPhoto: undefined,
  },
  newDerivation: {
    section: '',
    cableType: '',
    length: 0,
  },
  newMeter: {
    generation: '',
    serialNumber: '',
    key: '',
    dayIndex: '',
    nightIndex: '',
    indexPhoto: null,
  },
  circuitBreaker: {
    preserved: false,
    voltage: undefined,
    brand: '',
    type: undefined,
    power: '',
    commissioningDone: false,
    sealed: false,
  },
  photoAfterWork: {
    photo: null,
    secondPhoto: null,
    thirdPhoto: null,
    fourthPhoto: null,
  },
  clientValidation: {
    present: true,
    workValidation: false,
    satisfactionLevel: '0',
    clientComment: '',
    signature: null,
    technicianComment: '',
  },
};
