name: Deploy Turborepo Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build apps (only changed ones)
        run: yarn turbo run build --filter=...[HEAD^1]

      - name: Deploy Web to Vercel
        if: success()
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --scope sagbyy --cwd apps/web --prod

      - name: Deploy Api to Vercel
        if: success()
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --scope sagbyy --cwd apps/api --prod
