name: Deploy Turborepo Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.4
          run_install: false

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build apps
        run: pnpm turbo run build

      - name: Deploy Web to Vercel
        if: success()
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --scope sagbys-projects --cwd apps/web --prod --local-config dist/web

      - name: Deploy Api to Vercel
        if: success()
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --scope sagbys-projects --cwd apps/api --prod --local-config dist/api
